#Decodes the motec data into a ros message which can be logged into a mcap file
std_msgs/Header header  
float32 oil_temp
float32 coolant_temp
float32 oil_pressure
float32 engine_rpm
float32 throttle_position
float32 battery_voltage
int8 gear
int8 calculated_gear
float32 fuel_pressure
float32 front_brake_pressure
float32 rear_brake_pressure
float32 ecu_temp
float32 map_sensor
float32 wheel_speed
float32 intake_air_temp
